name: base
channels:
  - defaults
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python
  - numpy
  - pandas
  - openpyxl
  - plotly
  - Pillow
  - pip
  - pip:
    - streamlit
    - plotly
