name: base
channels:
  - defaults
  - conda-forge
  - anaconda
  - plotly
dependencies:
  - python
  - pandas=1.4.1
  - numpy
  - openpyxl
  - plotly
  - Pillow
  - pip
  - pip:
    - streamlit
